#!/usr/bin/env python3
"""
   Copyright 2017-2020 Semyon Yakimov
   This file is part of RogainingRoutes.
   RogainingRoutes is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.
   RogainingRoutes is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
   You should have received a copy of the GNU General Public License
   along with RogainingRoutes.  If not, see <http://www.gnu.org/licenses/>.
"""

import os
import math
import shutil
import argparse
import numpy as np
from jinja2 import Environment, FileSystemLoader, Template
import sfr
import sportorg
import splits_csv
import coursedata
from datetime import timedelta
from string import Template
from PIL import Image


javascript_map_scale = 1

course_color_min_speed = np.array((255, 0, 0))
course_color_avr_speed = np.array((255, 255, 0))
course_color_max_speed = np.array((0, 255, 0))
course_color_default = np.array((128, 128, 128))

env = Environment(
    loader=FileSystemLoader('templates'),
    trim_blocks=True,
    lstrip_blocks=True)

class DeltaTemplate(Template):
    delimiter = "%"

def strfdelta(tdelta):
    d = {}
    hours, rem = divmod(tdelta.seconds, 3600)
    mins, secs = divmod(rem, 60)
    fmt = '%H%M:%S'
    d['H'] = hours
    if hours > 0:
        d['M'] = '{:02d}'.format(mins)
    else:
        d['M'] = mins
        fmt = '%M:%S'
    d['S'] = '{:02d}'.format(secs)
    t = DeltaTemplate(fmt)
    return t.substitute(**d)

def tohhmmss(value):
    """value in minuts"""
    if value is None:
        return ''
    td = timedelta(minutes=value)
    return strfdelta(td)

def torgb(array):
    return 'rgb({},{},{})'.format(array[0], array[1], array[2])

env.filters['tohhmmss'] = tohhmmss
env.filters['torgb'] = torgb

def rotate(origin, point, angle):
    """
    Rotate a point counterclockwise by a given angle around a given origin.
    """
    ox, oy, *_ = origin
    px, py, *_ = point

    qx = ox + math.cos(angle) * (px - ox) - math.sin(angle) * (py - oy)
    qy = oy + math.sin(angle) * (px - ox) + math.cos(angle) * (py - oy)
    return qx, qy

def _round(p):
    return round(p[0]), round(p[1])

def colorSpeed(pos):
    ''' Linear interpolate from color course_color_min_speed (pos=0) to course_color_max_speed (pos=1)'''
    pos *= 2
    if pos <= 1:
        return ((1 - pos)*course_color_min_speed + pos*course_color_avr_speed).astype(int)
    pos -= 1
    return ((1 - pos)*course_color_avr_speed + pos*course_color_max_speed).astype(int)

def make_arrow(start, end):
    dx = end[0] - start[0]
    dy = end[1] - start[1]
    l = math.sqrt(dx**2 + dy**2)
    arrow_l = min(l*0.7, 30)
    arrow_ang = math.atan2(dy, dx)
    arrow = [
        (l, 2),
        (l - arrow_l, 7),
        (l - arrow_l, -7),
        (l, -2),
    ]
    arrow = [_round(rotate(start, (p[0] + start[0], p[1] + start[1]), arrow_ang)) for p in arrow]
    return arrow

def make_start_triangle(start, end):
    dx = end[0] - start[0]
    dy = end[1] - start[1]
    ang = math.atan2(dy, dx)
    l = min(math.sqrt(dx**2 + dy**2)*0.3, 15)
    polyline = (
        (l, 0),
        (-l*0.5, l*math.sqrt(3)/2),
        (-l*0.5, -l*math.sqrt(3)/2),
        (l, 0)
    )
    return [_round(rotate(start, (p[0] + start[0], p[1] + start[1]), ang)) for p in polyline]

def make_team_html(team, event_title, cp_coords, meters_in_pixel, map_filename, output_dir):
    team.full_name = team.get_team_full_name()
    title = '{} | {}'.format(team.full_name, event_title)
    team.penalty = team.sum - team.points
    if team.penalty < 0:
        team.penalty = 0
    table_titles = [
        'КП',
        'Время',
        'Сплит',
        'Очки',
        'Расстояние, км',
        'Темп, мин/км',
        'Мин/очко'
    ]

    start_x, start_y = cp_coords['start']
    start_offset_in_pixels = cp_coords['start_offset_in_pixels']
    rotate_angle = math.radians(cp_coords.get('rotate_angle', 0))
    cp_list = []
    data = []
    total_points = 0
    previos = [start_x, start_y]
    total_distance = 0
    fastest_pace = None
    slowest_pace = None

    for i in range(len(team.route)):
        cp = team.route[i]
        if isinstance(cp.id, int):
            x, y = cp_coords[cp.id]
        else:
            x = start_x
            y = start_y
        x_pixels = int((x - start_x)/meters_in_pixel) + start_offset_in_pixels[0]
        y_pixels = -int((y - start_y)/meters_in_pixel) + start_offset_in_pixels[1]

        total_points += cp.points

        leg_distance = math.sqrt((x - previos[0])**2 + (y - previos[1])**2)
        leg_distance /= 1000 # km
        total_distance += leg_distance

        previos[0] = x
        previos[1] = y

        pace = 0
        if cp.split and leg_distance != 0:
            pace = cp.split.total_seconds()/leg_distance/60
            if slowest_pace is None or slowest_pace < pace:
                slowest_pace = pace
            if fastest_pace is None or fastest_pace > pace:
                fastest_pace = pace
        cp_list.append((*_round(rotate(start_offset_in_pixels, (x_pixels, y_pixels), rotate_angle)), pace))

        minToPoints = 0
        if cp.points:
            minToPoints = cp.split.total_seconds()/cp.points/60

        d = [
            i,
            cp.id,
            cp.time or '',
            cp.split or '',
            '{} / {}'.format(cp.points, total_points) if cp.points > 0 else '',
            '{:.2f} / {:.2f}'.format(leg_distance, total_distance) if leg_distance > 0 else '',
            tohhmmss(pace) if pace else '',
            tohhmmss(minToPoints) if minToPoints else ''
        ]
        data.append(d)

    cp_list1 = []
    for i in range(len(cp_list)):
        cp = cp_list[i]
        pace = cp[2]
        color = course_color_default
        if pace > 0:
            color = colorSpeed((slowest_pace - pace)/(slowest_pace - fastest_pace))
        cp_list[i] = cp[0], cp[1], color

    avr_pace = team.time.total_seconds()/total_distance/60 if total_distance != 0 else 0
    total_effectiveness= team.time.total_seconds()/total_points/60 if total_points != 0 else 0 

    table_summary = [
        '',
        '',
        '',
        '',
        total_points,
        '{:.2f}'.format(total_distance),
        tohhmmss(avr_pace) if avr_pace else '',
        tohhmmss(total_effectiveness) if total_effectiveness else ''
    ]
    team.total_distance = total_distance
    team.avr_pace = avr_pace
    team.total_effectiveness = total_effectiveness
    team.planning_effectiveness = total_points/total_distance if total_distance != 0 else 0

    image =  Image.open(os.path.join(output_dir, map_filename))
    map_width, map_height = image.size

    start_triangle = make_start_triangle(cp_list[0], cp_list[1])
    cp_list[0] = start_triangle[0]

    template = env.get_template('team.html')
    with open(os.path.join(output_dir, team.get_team_html_name()), 'w') as fd:
        fd.write(template.render(
            title=title,
            team=team,
            table_titles=table_titles,
            table_summary=table_summary,
            map_file=map_filename,
            map_scale=javascript_map_scale,
            map_width=map_width,
            map_height=map_height,
            course_color_min_speed=course_color_min_speed,
            course_color_avr_speed=course_color_avr_speed,
            course_color_max_speed=course_color_max_speed,
            cp_list=cp_list,
            arrow=make_arrow(cp_list[0], cp_list[1]),
            start_triangle=start_triangle,
            data=data))
    return team


def make_result_html(teams, event_title, cp_coords, meters_in_pixel, map_filename, output_dir):
    print('Make result HTML')

    table_titles = [
        'Место',
        'Команда',
        'Участники',
        'Время',
        'Очки',
        'Штраф',
        'Итог',
        'Км',
        'Мин/очк'
    ]

    data = {}
    for group in teams:
        data[group] = [];
        for i in range(len(teams[group])):
            team = teams[group][i]
            teams[group][i] = make_team_html(team, event_title, cp_coords, meters_in_pixel, map_filename, output_dir)
            t = [
                team.place,
                '<a href="{}">{}</a>'.format(team.get_team_html_name(), team.get_team_full_name()),
                team.get_members_str(),
                team.time,
                team.sum,
                team.penalty if team.penalty > 0 else '',
                '<b>{}</b>'.format(team.points),
                '{:.2f}'.format(team.total_distance),
                '{:.2f}'.format(team.total_effectiveness),
            ]
            data[group].append(t)

    template = env.get_template('results.html')
    with open(os.path.join(output_dir, 'routes.html'), 'w') as fd:
        group_list = sorted(teams, reverse=True)
        fd.write(template.render(title=event_title, table_titles=table_titles, group_list=group_list, data=data))

def make_parser():
    parser = argparse.ArgumentParser(
        description='Command line utility to generate routes.',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('file', nargs='?', default='splits.html',
        help='splits SFR HTML file')
    parser.add_argument('-c', '--coords-file', default='coords.csv',
        help='coords CSV file')
    parser.add_argument('-m', '--map-file', default='map.jpg',
        help='map file')
    parser.add_argument('-d', '--map-dpi', type=int, default='72',
        help='map DPI')
    parser.add_argument('-l', '--map-scale', type=int, default='25000',
        help='map scale')
    parser.add_argument('-o', '--output-dir', default='output',
        help='output directory')
    return parser

if __name__ == '__main__':
    args,_ = make_parser().parse_known_args()

    input_filename_extension = os.path.splitext(args.file)[1]
    if input_filename_extension == '.json':
        teams, event_title = sportorg.parse_sportorg_result_json(args.file)
    elif input_filename_extension == '.csv':
        teams, event_title = splits_csv.parse_splits_csv(args.file)
    else:
        teams, event_title = sfr.parse_SFR_splits_html(args.file)
    cp_coords = coursedata.parse_course_data_file(args.coords_file)

    shutil.rmtree(args.output_dir, ignore_errors=True)
    os.mkdir(args.output_dir)

    output_map_filename = 'map' + os.path.splitext(args.map_file)[1]

    shutil.copy(args.map_file, os.path.join(args.output_dir, output_map_filename))
    shutil.copy('templates/style.css', args.output_dir)

    meters_in_pixel = args.map_scale*0.0254/args.map_dpi
    print('Meters in pixel:', meters_in_pixel)
    make_result_html(teams, event_title, cp_coords, meters_in_pixel, output_map_filename, args.output_dir)


